[build]
target-dir = "target"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    # Enable optimizations for mathematical operations
    "-C", "target-feature=+avx2,+fma",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-cpu=native", 
    "-C", "opt-level=3",
    "-C", "target-feature=+avx2,+fma",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3", 
    "-C", "target-feature=+avx2,+fma",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    # Use NEON for ARM64 Macs
    "-C", "target-feature=+neon",
]

# Profile optimizations for release builds
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1
debug = true

# Specific profile for benchmarking proof generation
[profile.bench]
opt-level = 3
lto = "fat" 
codegen-units = 1
debug = false